package com.ferreteria.vista;

import com.ferreteria.modelo.Usuario;
import java.awt.BorderLayout; // <--- IMPORTANTE: Necesitamos este import
import java.awt.Component;
import javax.swing.JFrame;
import raven.menu.MenuEvent; 

public class MainFrameFerreteria extends javax.swing.JFrame {

    // Se eliminó el atributo usuarioLogueado por ahora

    /**
     * Constructor Principal (Sin parámetros por ahora)
     */
    private Usuario usuarioLogueado;
public MainFrameFerreteria(Usuario usuario) {
        // 1. Guardamos la sesión ANTES de que NetBeans inicie los componentes
        this.usuarioLogueado = usuario;

        initComponents();
        
        // Ahora sí podemos usar la variable 'usuario' porque la recibimos arriba
        this.setTitle("Sistema Ferretería - Usuario: " + usuario.getNombreCompleto());

        // ==================================================================================
        // ---> CORRECCIÓN CRÍTICA Nº 1 (EL SALVAVIDAS) <---
        // Obligamos al panel 'body' a usar BorderLayout.
        body.setLayout(new BorderLayout());
        // ==================================================================================

        // Configuración básica de la ventana
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar
        this.setLocationRelativeTo(null); // Centrar

        // Configurar los eventos del menú lateral
        menu1.setEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex) {
                System.out.println("-> Cambiando a panel índice: " + index);
                // Llamamos al enrutador para que decida qué panel mostrar
                showForm(createForm(index, subIndex));
            }
        });

        // Cargar la primera pantalla por defecto.
        System.out.println("-> Cargando Dashboard inicial...");
        showForm(new PanelDashboard());
    }

    // Se eliminó el getter getUsuarioLogueado() por ahora

    // ==================================================================================
    // EL "ENRUTADOR" PRINCIPAL
    // Mapea los índices del menú a los paneles correspondientes.
    // ==================================================================================
    private Component createForm(int index, int subIndex) {
        switch (index) {
            case 0: // Título "FERRETERIA CRUZ"
            case 1: // Botón "Inicio"
                return new PanelDashboard();
            case 2: // Botón "Ventas"
return new PanelVentas(this.usuarioLogueado);
            case 3: // Botón "Inventario"
                return new PanelInventario();
            case 4: // Botón "Proveedores"
                return new PanelProveedores();
            case 5: // Botón "Reportes"
                return new PanelReportes();
            case 6: // Botón "Proveedores"
                return new PanelProveedores();
            case 7: // Botón "Salir"
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desea salir de la aplicación?", "Salir", javax.swing.JOptionPane.YES_NO_OPTION);
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    this.dispose(); // Cierra la ventana
                    System.exit(0); // Cierra toda la aplicación
                }
                return null; // No devuelve ningún panel nuevo
            default:
                return new javax.swing.JPanel(); // Panel vacío por si acaso
        }
    }

    // ==================================================================================
    // ---> CORRECCIÓN CRÍTICA Nº 2 (EL REFRESCO) <---
    // Este método cambia el panel central y fuerza a Java a repintarlo.
    // ==================================================================================
    private void showForm(Component com) {
        if (com == null) return; // Si es el botón salir, no hacemos nada

        // 1. Quitar el panel viejo del contenedor 'body'
        body.removeAll();
        
        // 2. Agregar el nuevo panel al centro.
        // Al usar BorderLayout.CENTER (configurado en el constructor), se estirará.
        body.add(com, BorderLayout.CENTER);
        
        // 3. ¡FUERZA BRUTA! Obligar a Java a recalcular el diseño y repintar los píxeles.
        body.revalidate();
        body.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        polygonCorner1 = new raven.scroll.win11.PolygonCorner();
        polygonCorner2 = new raven.scroll.win11.PolygonCorner();
        jMenu1 = new javax.swing.JMenu();
        menu2 = new raven.menu.Menu();
        jPanel1 = new javax.swing.JPanel();
        menupnl = new raven.scroll.win11.ScrollPaneWin11();
        menu1 = new raven.menu.Menu();
        jPanel4 = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menupnl.setBorder(null);
        menupnl.setViewportView(menu1);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-abierto.png"))); // NOI18N
        btnMenu1.setBorder(null);
        btnMenu1.setContentAreaFilled(false);
        btnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnMenu1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnMenu1)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 756, 37, -1));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menupnl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menupnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        // TODO add your handling code here:
           if (menupnl.isVisible()) {
        menupnl.setVisible(false);
    } else {
        // Si el menú está oculto, lo mostramos y el body vuelve a su tamaño normal
        menupnl.setVisible(true);
    }

    // Forzar que el contenedor vuelva a calcular tamaños
    jPanel1.revalidate();
    jPanel1.repaint();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameFerreteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                // --- SOLUCIÓN AL ERROR ---
                // Como ahora el constructor pide un Usuario, creamos uno "falso" 
                // solo para que este método de prueba funcione.
                
                Usuario usuarioPrueba = new Usuario();
                // OJO: Necesitas importar com.ferreteria.modelo.Usuario arriba si da error aquí
                usuarioPrueba.setIdUsuario(999);
                usuarioPrueba.setNombreCompleto("Usuario de Prueba (Admin)");
                // usuarioPrueba.setRol("Administrador"); // Si usas roles
                
                // Ahora sí, abrimos la ventana pasándole el usuario de prueba
                new MainFrameFerreteria(usuarioPrueba).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private raven.menu.Menu menu1;
    private raven.menu.Menu menu2;
    private raven.scroll.win11.ScrollPaneWin11 menupnl;
    private raven.scroll.win11.PolygonCorner polygonCorner1;
    private raven.scroll.win11.PolygonCorner polygonCorner2;
    // End of variables declaration//GEN-END:variables
}
