package com.ferreteria.vista;

import com.ferreteria.dao.ProductoDAOImpl;
import com.ferreteria.modelo.Producto;
import com.ferreteria.util.ComboBoxItem;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class PanelListadoProductos extends javax.swing.JPanel {

    private ProductoDAOImpl productoDAO = new ProductoDAOImpl();

    public PanelListadoProductos() {
        initComponents();
        configurarTabla();
        cargarDatosIniciales();
    }

    private void configurarTabla() {
        // Columnas basadas en tu diseño visual
        String[] titulos = {"Código", "Categoría", "Marca/Material", "Modelo Producto", "Precio", "Stock", "Ubicación"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloqueado para que el vendedor no edite nada
            }
        };
        tablaCatalogo.setModel(modelo);
    }

   private void cargarDatosIniciales() {
        // 1. Cargar combo de Categorías
        List<ComboBoxItem> listaCat = productoDAO.listarCategoriasCombo();
        cmbCategoria1.removeAllItems();
        cmbCategoria1.addItem("Seleccione categoría"); 
        for (ComboBoxItem item : listaCat) {
            cmbCategoria1.addItem(item.toString());
        }

        // 2. Cargar MARCAS (Usando el combo cmbMaterial1)
        cmbMaterial1.removeAllItems();
        cmbMaterial1.addItem("Seleccione marca");
        
        // Truco PRO: Extraer las marcas únicas automáticamente de tu base de datos
        List<Producto> todosLosProductos = productoDAO.listarTodos(false);
        java.util.Set<String> marcasUnicas = new java.util.HashSet<>();
        
        for (Producto p : todosLosProductos) {
            if (p.getMarca() != null && !p.getMarca().trim().isEmpty()) {
                // Guardamos la marca (la convertimos a mayúsculas para evitar duplicados como "Bosch" y "BOSCH")
                marcasUnicas.add(p.getMarca().toUpperCase()); 
            }
        }
        // Llenar el ComboBox con las marcas encontradas
        for (String marca : marcasUnicas) {
            cmbMaterial1.addItem(marca);
        }

        // 3. Llenar combo de Precio
        cmbPrecio1.removeAllItems();
        cmbPrecio1.addItem("Seleccione precio");
        cmbPrecio1.addItem("Menor a S/50");
        cmbPrecio1.addItem("S/50 a S/100");
        cmbPrecio1.addItem("Mayor a S/100");

        // 4. Llenar combo de Stock
        cmbStock1.removeAllItems();
        cmbStock1.addItem("Seleccione stock");
        cmbStock1.addItem("En Stock (>0)");
        cmbStock1.addItem("Sin Stock (0)");

        // Mostrar todos los productos al abrir
        cargarTablaTodos();
    }

    private void cargarTablaTodos() {
        llenarTabla(productoDAO.listarTodos(false)); // false = solo activos
    }

    private void llenarTabla(List<Producto> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tablaCatalogo.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Producto p : lista) {
            Object[] fila = {
                p.getCodigo(),
                p.getIdCategoria(), // Idealmente aquí iría el nombre de la categoría cruzado con la BD
                p.getMarca(),
                p.getNombre(),
                String.format("%.2f", p.getPrecioVenta()),
                p.getStockActual(),
                p.getUbicacion()
            };
            modelo.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cmbCategoria1 = new javax.swing.JComboBox<>();
        cmbMaterial1 = new javax.swing.JComboBox<>();
        cmbPrecio1 = new javax.swing.JComboBox<>();
        cmbStock1 = new javax.swing.JComboBox<>();
        btnFiltroCategoria = new javax.swing.JButton();
        FiltroStock = new javax.swing.JButton();
        btnFiltroMaterial = new javax.swing.JButton();
        btnFiltroPrecio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        btnRestaurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        cmbCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbMaterial1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPrecio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbStock1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFiltroCategoria.setText("FiltroCategoria");
        btnFiltroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroCategoriaActionPerformed(evt);
            }
        });

        FiltroStock.setText("jButton1");
        FiltroStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroStockActionPerformed(evt);
            }
        });

        btnFiltroMaterial.setText("FiltroMaterial");
        btnFiltroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroMaterialActionPerformed(evt);
            }
        });

        btnFiltroPrecio.setText("FiltroPrecio");
        btnFiltroPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroPrecioActionPerformed(evt);
            }
        });

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCatalogo);

        btnRestaurar.setText("jButton1");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        jLabel1.setText("categoria:");

        jLabel2.setText("material:");

        jLabel3.setText("Precio");

        jLabel4.setText("stock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnRestaurar)))
                .addGap(0, 133, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(cmbPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(cmbStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FiltroStock, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnFiltroMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(btnFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FiltroStock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroCategoriaActionPerformed
   int indexSeleccionado = cmbCategoria1.getSelectedIndex();
        if (indexSeleccionado > 0) { // Si no es la opción "Seleccione categoría"
            // Nota: Para este ejemplo básico, estamos usando el índice del combo asumiendo que coincide con el ID
            // En una versión final, deberás recuperar el ID real de la categoría
            List<Producto> resultados = productoDAO.listarPorCategoria(indexSeleccionado);
            llenarTabla(resultados);
        } else {
            cargarTablaTodos();
        }
    }//GEN-LAST:event_btnFiltroCategoriaActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
   cmbCategoria1.setSelectedIndex(0);
        cmbMaterial1.setSelectedIndex(0);
        cmbPrecio1.setSelectedIndex(0);
        cmbStock1.setSelectedIndex(0);
        cargarTablaTodos();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnFiltroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroMaterialActionPerformed
      // =========================================================
    // FILTRO DE MARCAS (Usa el botón y combo de "Material")
    // =========================================================
        int index = cmbMaterial1.getSelectedIndex();
        
        if (index > 0) { // Si eligió una marca de la lista
            // Obtenemos la marca elegida en el combo
            String marcaElegida = cmbMaterial1.getSelectedItem().toString().toLowerCase();
            
            List<Producto> todos = productoDAO.listarTodos(false);
            List<Producto> filtrados = new java.util.ArrayList<>();
            
            for (Producto p : todos) {
                // Solo miramos la columna "marca" del producto
                String marcaProducto = p.getMarca() != null ? p.getMarca().toLowerCase() : "";
                
                if (marcaProducto.equals(marcaElegida)) {
                    filtrados.add(p);
                }
            }
            llenarTabla(filtrados);
        } else {
            cargarTablaTodos();
        }
    
    }//GEN-LAST:event_btnFiltroMaterialActionPerformed

    private void FiltroStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroStockActionPerformed
 int index = cmbStock1.getSelectedIndex();
        if (index > 0) {
            List<Producto> todos = productoDAO.listarTodos(false);
            List<Producto> filtrados = new java.util.ArrayList<>();
            
            for (Producto p : todos) {
                int stock = p.getStockActual(); // Usamos el stock del modelo
                
                if (index == 1 && stock > 0) { 
                    // Opción: "En Stock (>0)"
                    filtrados.add(p);
                } else if (index == 2 && stock == 0) { 
                    // Opción: "Sin Stock (0)"
                    filtrados.add(p);
                }
            }
            llenarTabla(filtrados);
        } else {
            cargarTablaTodos();
        }
    }//GEN-LAST:event_FiltroStockActionPerformed

    private void btnFiltroPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroPrecioActionPerformed
        // TODO add your handling code here:
        int index = cmbPrecio1.getSelectedIndex();
        if (index > 0) {
            List<Producto> todos = productoDAO.listarTodos(false);
            List<Producto> filtrados = new java.util.ArrayList<>();
            
            for (Producto p : todos) {
                double precio = p.getPrecioVenta(); // Usamos el precio del modelo
                
                if (index == 1 && precio < 50.0) { 
                    // Opción: "Menor a S/50"
                    filtrados.add(p);
                } else if (index == 2 && precio >= 50.0 && precio <= 100.0) { 
                    // Opción: "S/50 a S/100"
                    filtrados.add(p);
                } else if (index == 3 && precio > 100.0) { 
                    // Opción: "Mayor a S/100"
                    filtrados.add(p);
                }
            }
            llenarTabla(filtrados);
        } else {
            cargarTablaTodos();
        }
    }//GEN-LAST:event_btnFiltroPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FiltroStock;
    private javax.swing.JButton btnFiltroCategoria;
    private javax.swing.JButton btnFiltroMaterial;
    private javax.swing.JButton btnFiltroPrecio;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JComboBox<String> cmbCategoria1;
    private javax.swing.JComboBox<String> cmbMaterial1;
    private javax.swing.JComboBox<String> cmbPrecio1;
    private javax.swing.JComboBox<String> cmbStock1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCatalogo;
    // End of variables declaration//GEN-END:variables
}
