/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Component;
import modelo.Alumno;
import paneles.CAlumno;
import paneles.CCurso;
import paneles.DefaultForm;
import paneles.HomeForm;
import paneles.MAlumno;
import paneles.MCurso;
import paneles.RAlumno;
import paneles.RCurso;
import paneles.lorena;
import paneles.reporteAlumno;
import paneles.reporteCurso;
import raven.menu.MenuEvent;


/**
 *
 * @author USUARIO
 */
public class finalmenu extends javax.swing.JFrame {

   private Alumno alumnoLogueado; // ⬅️ AGREGAR ESTO
    
    // Constructor SIN parámetros (para compatibilidad)
    public finalmenu() {
        this(null); // Llama al constructor con parámetro
    }
    
    // Constructor CON alumno logueado ⬅️ NUEVO
    public finalmenu(Alumno alumno) {
        this.alumnoLogueado = alumno;
        initComponents();
        
        // Ajusta tamaño base
        this.setSize(1200, 800);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        // Configura el evento del menú
        menu1.setEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex) {
                showForm(createForm(index, subIndex));
            }
        });
        
        // Opcional: Mostrar el nombre del alumno en algún label
        if (alumnoLogueado != null) {
            System.out.println("Usuario logueado: " + alumnoLogueado.getNombres());
        }
    }
    
    // Getter para obtener el alumno logueado
    public Alumno getAlumnoLogueado() {
        return alumnoLogueado;
    }
    
    private Component createForm(int index, int subIndex) {
        switch (index) {
            case 0: // Home
                return new HomeForm();
                
            case 1: // Mantenimiento
                switch (subIndex) {
                    case 1:
                        return new MAlumno();
                    case 2:
                        return new MCurso();
                    default:
                        return new DefaultForm("Mantenimiento - sin submenú");
                }
                
            case 2: // Reportes
                switch (subIndex) {
                    case 1:
                        return new RAlumno();
                    case 2:
                        return new RCurso();
                    case 3:
                        return new lorena();
                    default:
                        return new DefaultForm("Reportes - sin submenú");
                }
                
           case 3:
                switch (subIndex) {
                case 1:
                    return new CAlumno(); // <-- tu panel "r.alumno"
                case 2:
                    return new CCurso();   // <-- tu panel "r.curso"
                default:
                    return new DefaultForm("nada - sin submenú");
            }
                
            case 4: // Reporte
                switch (subIndex) {
                    case 1:
                        return new reporteAlumno();
                    case 2:
                        return new reporteCurso();
                    default:
                        return new DefaultForm("Reporte - sin submenú");
                }
                
            case 5: // Salir
JFLogin regreso= new JFLogin();
regreso.setVisible(true);
this.dispose();
              
            default:
                return new DefaultForm("Desconocido: index=" + index + " subIndex=" + subIndex);
        }
    }
    
    private void showForm(Component com) {
        body.removeAll();
        body.setLayout(new java.awt.BorderLayout());
        body.add(com, java.awt.BorderLayout.CENTER);
        body.repaint();
        body.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        polygonCorner1 = new raven.scroll.win11.PolygonCorner();
        polygonCorner2 = new raven.scroll.win11.PolygonCorner();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        menupnl = new raven.scroll.win11.ScrollPaneWin11();
        menu1 = new raven.menu.Menu();
        jPanel4 = new javax.swing.JPanel();
        btnMenu2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menupnl.setBorder(null);

        menu1.setBackground(new java.awt.Color(0, 102, 102));
        menu1.setForeground(new java.awt.Color(0, 102, 102));
        menupnl.setViewportView(menu1);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-abierto.png"))); // NOI18N
        btnMenu2.setBorder(null);
        btnMenu2.setContentAreaFilled(false);
        btnMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UTPLOGO (1).jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 756, 37, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChatGPT Image 25 nov 2025, 01_19_47 p.m. (5).png"))); // NOI18N
        body.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 490, -1));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menupnl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menupnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
// TODO add your handling code here:
           if (menupnl.isVisible()) {
        menupnl.setVisible(false);
    } else {
        // Si el menú está oculto, lo mostramos y el body vuelve a su tamaño normal
        menupnl.setVisible(true);
    }

    // Forzar que el contenedor vuelva a calcular tamaños
    jPanel1.revalidate();
    jPanel1.repaint();
    }//GEN-LAST:event_btnMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private raven.menu.Menu menu1;
    private raven.scroll.win11.ScrollPaneWin11 menupnl;
    private raven.scroll.win11.PolygonCorner polygonCorner1;
    private raven.scroll.win11.PolygonCorner polygonCorner2;
    // End of variables declaration//GEN-END:variables
}
