/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import interfaces.finalmenu;
import dao.AdminDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.Admin;
import dao.AlumnoDAO;
import javax.swing.JPasswordField;
import modelo.Alumno;

/**
 *
 * @author Cesar
 */
public class JFLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFLogin.class.getName());
private javax.swing.ButtonGroup buttonGroup;
    /**
     * Creates new form JFLogin
     */
    
    private void configurarLabels() {
    // Hacer que todos los labels tengan el mismo ancho mínimo
    int anchoMinimo = 150;
    jLabel4.setPreferredSize(new java.awt.Dimension(anchoMinimo, jLabel4.getPreferredSize().height));
    jLabel12.setPreferredSize(new java.awt.Dimension(anchoMinimo, jLabel12.getPreferredSize().height));
    jLabel13.setPreferredSize(new java.awt.Dimension(anchoMinimo, jLabel13.getPreferredSize().height));
}



    private void configurarVista() {
    // Inicialmente mostrar vista de Admin
    mostrarVistaAdmin();
    rbAdmin.setSelected(true);
}

private void configurarRadioButtons() {
    // Listener para rbAdmin
    rbAdmin.addActionListener(e -> mostrarVistaAdmin());
    
    // Listener para rbAlumno
    rbAlumno.addActionListener(e -> mostrarVistaAlumno());
}

private void mostrarVistaAdmin() {
    // Cambiar los textos de los labels
    jLabel4.setText("USUARIO:");
    jLabel12.setText("CONTRASEÑA:");
    jLabel13.setText("NOMBRE:");
    
   
    // Mostrar los 3 campos
    txtUsuario.setVisible(true);
    txtPassword.setVisible(true);
    txtNombre.setVisible(true);
    
    // Ocultar label y campo DNI
    jLabel5.setVisible(false);
    txtDNI.setVisible(false);
    
    // Limpiar campos
    limpiarCampos();
}

private void mostrarVistaAlumno() {
    // Cambiar los textos de los labels
    jLabel4.setText("DNI:");
    jLabel12.setText("CONTRASEÑA:");
    jLabel13.setText("NOMBRE:");  // ⬅️ AHORA SÍ MOSTRAR EL TERCER CAMPO
    
    // Activar el ocultamiento de contraseña
    txtPassword.setEchoChar('*');
    
    // Mostrar los 3 campos
    txtUsuario.setVisible(true);
    txtPassword.setVisible(true);
    txtNombre.setVisible(true);  // ⬅️ MOSTRAR EL TERCER CAMPO
    
    // Ocultar label y campo DNI extra
    jLabel5.setVisible(false);
    txtDNI.setVisible(false);
    
    // Limpiar campos
    limpiarCampos();
}

private void limpiarCampos() {
    txtUsuario.setText("");
    txtPassword.setText("");
    txtNombre.setText("");
    txtDNI.setText("");
}
    
    
    private void mostrarError() {
        JOptionPane.showMessageDialog(this,
                "Correo o contraseña incorrectos",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    private String capitalizarNombre(String nombre) {
        if (nombre == null || nombre.isEmpty()) {
            return nombre;
        }
        return nombre.substring(0, 1).toUpperCase() + nombre.substring(1).toLowerCase();
    }

    public JFLogin() {
        initComponents();
        setLocationRelativeTo(null);
        
        configurarLabels();
        
         buttonGroup = new javax.swing.ButtonGroup();
    buttonGroup.add(rbAdmin);
    buttonGroup.add(rbAlumno);
        
        configurarVista();
    configurarRadioButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbAlumno = new javax.swing.JRadioButton();
        rbAdmin = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnAccesoAdmin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CORREO:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("iniciar como:");

        rbAlumno.setForeground(new java.awt.Color(255, 255, 255));
        rbAlumno.setText("ALUMNO");
        rbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlumnoActionPerformed(evt);
            }
        });

        rbAdmin.setForeground(new java.awt.Color(255, 255, 255));
        rbAdmin.setText("ADMIN");
        rbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdminActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("¿ERES ADMINISTRADOR?");

        btnIniciarSesion.setBackground(new java.awt.Color(255, 153, 51));
        btnIniciarSesion.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnAccesoAdmin.setBackground(new java.awt.Color(204, 153, 0));
        btnAccesoAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAccesoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAccesoAdmin.setText("REGISTRAR");
        btnAccesoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoAdminActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setToolTipText("");

        jLabel10.setText("jLabel7");

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CONTRASEÑA:");

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NOMBRE:");

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("INICIAR SESION");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAccesoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(53, 53, 53)
                                        .addComponent(rbAdmin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbAlumno)))
                                .addGap(148, 148, 148)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtPassword)
                                    .addComponent(txtNombre)
                                    .addComponent(txtDNI))))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rbAdmin)
                            .addComponent(rbAlumno))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccesoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoAdminActionPerformed


    // Pedir solo la contraseña
    String passwordIngresada = JOptionPane.showInputDialog(this, 
        "Ingrese la contraseña de administrador:", 
        "Acceso Administrador", 
        JOptionPane.PLAIN_MESSAGE);
    
    // Si presionó cancelar o no ingresó nada
    if (passwordIngresada == null || passwordIngresada.trim().isEmpty()) {
        return;
    }
    
    // Validar contraseña
    AdminDAO adminDAO = new AdminDAO();
    Admin admin = adminDAO.loginAdminSoloPassword(passwordIngresada.trim());
    
    if (admin != null) {
        // Contraseña correcta
        this.setVisible(false);
        JFRegistroAlumnos registroAlumnos = new JFRegistroAlumnos();
        registroAlumnos.setVisible(true);
        this.dispose();
    } else {
        // Contraseña incorrecta
        JOptionPane.showMessageDialog(this,
            "Contraseña incorrecta",
            "Acceso denegado",
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnAccesoAdminActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed


    
    if (rbAdmin.isSelected()) {
        // ============ LOGIN ADMIN ============
        // Validar que los 3 campos no estén vacíos
        if (txtUsuario.getText().trim().isEmpty() || 
            String.valueOf(txtPassword.getPassword()).trim().isEmpty() || 
            txtNombre.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this,
                "Por favor complete todos los campos",
                "Campos vacíos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String usuario = txtUsuario.getText().trim();
        String password = String.valueOf(txtPassword.getPassword()).trim();
        String nombre = txtNombre.getText().trim();
        
        AdminDAO adminDAO = new AdminDAO();
        Admin admin = adminDAO.loginAdmin(usuario, password, nombre);
        
        if (admin != null) {
            JOptionPane.showMessageDialog(this,
                "¡Bienvenido " + admin.getNombre() + "!",
                "Login exitoso",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Aquí abrirías el menú principal del admin
            // this.dispose();
            // JFMenuAdmin menuAdmin = new JFMenuAdmin();
            // menuAdmin.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this,
                "Usuario no encontrado o credenciales incorrectas",
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } else if (rbAlumno.isSelected()) {
    // ============ LOGIN ALUMNO ============
    // Validar que los 3 campos no estén vacíos
    if (txtUsuario.getText().trim().isEmpty() || 
        String.valueOf(txtPassword.getPassword()).trim().isEmpty() || 
        txtNombre.getText().trim().isEmpty()) {
        
        JOptionPane.showMessageDialog(this,
            "Por favor complete todos los campos",
            "Campos vacíos",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String dni = txtUsuario.getText().trim();
    String password = String.valueOf(txtPassword.getPassword()).trim();
    String nombres = txtNombre.getText().trim();
    
    dao.AlumnoDAO alumnoDAO = new dao.AlumnoDAO();
    modelo.Alumno alumno = alumnoDAO.loginAlumno(dni, password, nombres);
    
    if (alumno != null) {
        JOptionPane.showMessageDialog(this,
            "¡Bienvenido " + alumno.getNombres() + "!",
            "Login exitoso",
            JOptionPane.INFORMATION_MESSAGE);
        
        // Abrir finalmenu en lugar de JFRegistroAlumnos
        this.dispose();
        finalmenu menuAlumno = new finalmenu();  // ⬅️ CAMBIO AQUÍ
        menuAlumno.setVisible(true);
        
    } else {
        JOptionPane.showMessageDialog(this,
            "DNI, contraseña o nombre incorrectos",
            "Error de autenticación",
            JOptionPane.ERROR_MESSAGE);
    }
    
} else {
        JOptionPane.showMessageDialog(this,
            "Por favor selecciona Admin o Alumno",
            "Selección requerida",
            JOptionPane.WARNING_MESSAGE);
    }

        
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void rbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAdminActionPerformed

    private void rbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAlumnoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccesoAdmin;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbAlumno;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
