package paneles;
import dao.AlumnoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;

public class MAlumno extends javax.swing.JPanel {
 private AlumnoDAO alumnoDAO;
    private DefaultTableModel modeloTabla;
    private int codigoSeleccionado = -1;
    
    public MAlumno() {
        initComponents();
        alumnoDAO = new AlumnoDAO();

        configurarTabla();
        cargarDatosTabla();

        txtCodAlumno.setEditable(false);
        lblEstado2.setText("Registrado");
    }
private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"Código", "Nombres", "Apellidos", "DNI", "Edad", "Celular", "Estado"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblAlumnos.setModel(modeloTabla);
        tblAlumnos.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarDatosTabla() {
        modeloTabla.setRowCount(0);
        List<Alumno> alumnos = alumnoDAO.listarAlumnos();
        for (Alumno a : alumnos) {
            Object[] fila = {
                a.getCodAlumno(),
                a.getNombres(),
                a.getApellidos(),
                a.getDni(),
                a.getEdad(),
                a.getCelular(),
                a.getEstadoTexto()
            };
            modeloTabla.addRow(fila);
        }
    }
  private int generarCodigo() {
        int max = 0;
        List<Alumno> alumnos = alumnoDAO.listarAlumnos();
        for (Alumno a : alumnos) {
            if (a.getCodAlumno() > max) {
                max = a.getCodAlumno();
            }
        }
        return max + 1;
    }

    private boolean dniExiste(String dni) {
        Alumno a = alumnoDAO.buscarPorDNI(dni);
        return a != null;
    }

    private void limpiarCampos() {
       txtCodAlumno.setText("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtDni.setText("");
    txtEdad.setText("");
    txtCelular.setText("");
    lblEstado2.setText("Registrado");
    tblAlumnos.clearSelection();
    txtDni.setEditable(true); // IMPORTANTE: para nuevo registro
    }

    private void cargarSeleccionadoEnCampos(int fila) {
        if (fila == -1) return;

        codigoSeleccionado = (int) tblAlumnos.getValueAt(fila, 0);

        txtCodAlumno.setText(tblAlumnos.getValueAt(fila, 0).toString());
        txtNombres.setText(tblAlumnos.getValueAt(fila, 1).toString());
        txtApellidos.setText(tblAlumnos.getValueAt(fila, 2).toString());
        txtDni.setText(tblAlumnos.getValueAt(fila, 3).toString());
        txtEdad.setText(tblAlumnos.getValueAt(fila, 4).toString());
        txtCelular.setText(tblAlumnos.getValueAt(fila, 5).toString());
        lblEstado2.setText(tblAlumnos.getValueAt(fila, 6).toString());
    }

    private boolean validarCampos() {
        if (txtNombres.getText().trim().isEmpty()
                || txtApellidos.getText().trim().isEmpty()
                || txtDni.getText().trim().isEmpty()
                || txtEdad.getText().trim().isEmpty()
                || txtCelular.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos.",
                    "Campos vacíos",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (!txtDni.getText().trim().matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this,
                    "El DNI debe tener 8 dígitos.",
                    "DNI inválido",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        try {
            Integer.parseInt(txtEdad.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Edad inválida.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            Integer.parseInt(txtCelular.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Celular inválido.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        panelAlumno = new javax.swing.JPanel();
        lblTitulo9 = new javax.swing.JLabel();
        lblApellidos2 = new javax.swing.JLabel();
        lblDni2 = new javax.swing.JLabel();
        txtCodAlumno = new javax.swing.JTextField();
        lblEdad2 = new javax.swing.JLabel();
        lblCelular2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblEstado2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        lblCodAlumno2 = new javax.swing.JLabel();
        lblNombres2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(243, 156, 18));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(243, 156, 18));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setMaximumSize(new java.awt.Dimension(80, 23));
        btnNuevo.setMinimumSize(new java.awt.Dimension(80, 23));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(243, 156, 18));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar/Limpiar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(231, 28, 36));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "DNI", "Edad", "Celular", "Estado"
            }
        ));
        tblAlumnos.setShowHorizontalLines(true);
        tblAlumnos.setShowVerticalLines(true);
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAlumnos);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setForeground(new java.awt.Color(153, 204, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(880, 70));

        lblTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo4.setText("MANTENIMIENTO DE ALUMNO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(lblTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(271, 271, 271))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        panelAlumno.setBackground(new java.awt.Color(248, 249, 250));
        panelAlumno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        panelAlumno.setToolTipText("");
        panelAlumno.setName(""); // NOI18N
        panelAlumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo9.setBackground(new java.awt.Color(25, 42, 86));
        lblTitulo9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo9.setForeground(new java.awt.Color(25, 42, 86));
        lblTitulo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo9.setText("DATOS DEL ALUMNO:");
        panelAlumno.add(lblTitulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, -1, -1));

        lblApellidos2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidos2.setText("Apellido:");
        panelAlumno.add(lblApellidos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, 150, 32));

        lblDni2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDni2.setText("DNI:");
        panelAlumno.add(lblDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 183, 150, 32));

        txtCodAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAlumnoActionPerformed(evt);
            }
        });
        panelAlumno.add(txtCodAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 234, 32));

        lblEdad2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEdad2.setText("Edad:");
        panelAlumno.add(lblEdad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 233, 150, 32));

        lblCelular2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCelular2.setText("Celular:");
        panelAlumno.add(lblCelular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 285, 150, 32));

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        panelAlumno.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 234, 35));

        lblEstado2.setText("jLabel7");
        panelAlumno.add(lblEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 338, 122, 24));

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        panelAlumno.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 234, 36));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        panelAlumno.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 234, 32));
        panelAlumno.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 234, 32));
        panelAlumno.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 234, 32));

        lblCodAlumno2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodAlumno2.setText("Codigo:");
        panelAlumno.add(lblCodAlumno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 27, 150, 32));

        lblNombres2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombres2.setText("Nombre:");
        panelAlumno.add(lblNombres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 32));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(41, 128, 185));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("🔍 Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     String dni = txtBuscar.getText().trim();

    if (dni.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un DNI para buscar.");
        return;
    }
    if (!dni.matches("\\d{8}")) {
        JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos.");
        return;
    }

    Alumno encontrado = alumnoDAO.buscarPorDNI(dni);

    if (encontrado != null) {
        txtCodAlumno.setText(String.valueOf(encontrado.getCodAlumno()));
        txtNombres.setText(encontrado.getNombres());
        txtApellidos.setText(encontrado.getApellidos());
        txtDni.setText(encontrado.getDni());
        txtEdad.setText(String.valueOf(encontrado.getEdad()));
        txtCelular.setText(String.valueOf(encontrado.getCelular()));
        lblEstado2.setText(encontrado.getEstadoTexto());

        // seleccionar en la tabla
        for (int i = 0; i < tblAlumnos.getRowCount(); i++) {
            int cod = (int) tblAlumnos.getValueAt(i, 0);
            if (cod == encontrado.getCodAlumno()) {
                tblAlumnos.setRowSelectionInterval(i, i);
                tblAlumnos.scrollRectToVisible(tblAlumnos.getCellRect(i, 0, true));
                break;
            }
        }

        JOptionPane.showMessageDialog(this, "Alumno encontrado.");
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró un alumno con ese DNI.");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       if (txtCodAlumno.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un alumno de la tabla.");
        return;
    }

    if (!validarCampos()) return;

    Alumno alu = new Alumno();
    alu.setCodAlumno(Integer.parseInt(txtCodAlumno.getText().trim()));
    alu.setNombres(txtNombres.getText().trim());
    alu.setApellidos(txtApellidos.getText().trim());
    alu.setDni(txtDni.getText().trim()); // no editable desde UI
    alu.setEdad(Integer.parseInt(txtEdad.getText().trim()));
    alu.setCelular(Integer.parseInt(txtCelular.getText().trim()));

    // mantener el mismo estado actual
    String estado = lblEstado2.getText();
    if (estado.equalsIgnoreCase("Registrado")) alu.setEstado(0);
    else if (estado.equalsIgnoreCase("Matriculado")) alu.setEstado(1);
    else if (estado.equalsIgnoreCase("Retirado")) alu.setEstado(2);

    if (alumnoDAO.actualizarAlumno(alu)) {
        JOptionPane.showMessageDialog(this, "Alumno modificado correctamente.");
        limpiarCampos();
        cargarDatosTabla();
    } else {
        JOptionPane.showMessageDialog(this, "Error al modificar el alumno.");
    }   

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      
          limpiarCampos();
    int nuevoCodigo = generarCodigo();
    txtCodAlumno.setText(String.valueOf(nuevoCodigo));
    lblEstado2.setText("Registrado");
    txtDni.setEditable(true); // se puede escribir DNI para un nuevo alumno  
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     
 if (!validarCampos()) return;

    String dni = txtDni.getText().trim();
    if (!dni.matches("\\d{8}")) {
        JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos.");
        return;
    }

    // verificar duplicado
    Alumno existe = alumnoDAO.buscarPorDNI(dni);
    if (existe != null) {
        JOptionPane.showMessageDialog(this, "El DNI ya está registrado.");
        return;
    }

    int cod = Integer.parseInt(txtCodAlumno.getText().trim());
    Alumno alu = new Alumno();
    alu.setCodAlumno(cod);
    alu.setNombres(txtNombres.getText().trim());
    alu.setApellidos(txtApellidos.getText().trim());
    alu.setDni(dni);
    alu.setEdad(Integer.parseInt(txtEdad.getText().trim()));
    alu.setCelular(Integer.parseInt(txtCelular.getText().trim()));
    alu.setEstado(0); // 0 = Registrado

    if (alumnoDAO.insertarAlumno(alu)) {
        JOptionPane.showMessageDialog(this, "Alumno registrado correctamente.");
        limpiarCampos();
        cargarDatosTabla();
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar el alumno.");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed


// TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if (txtCodAlumno.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un alumno de la tabla.");
        return;
    }

    String estado = lblEstado2.getText();
    if (!estado.equalsIgnoreCase("Registrado")) {
        JOptionPane.showMessageDialog(this,
                "Solo se puede eliminar alumnos con estado 0 (Registrado).",
                "No permitido",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int cod = Integer.parseInt(txtCodAlumno.getText().trim());
    int r = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este alumno?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

    if (r == JOptionPane.YES_OPTION) {
        if (alumnoDAO.eliminarAlumno(cod)) {
            JOptionPane.showMessageDialog(this, "Alumno eliminado correctamente.");
            limpiarCampos();
            cargarDatosTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el alumno.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
    int fila = tblAlumnos.getSelectedRow();
    if (fila == -1) return;

    txtCodAlumno.setText(tblAlumnos.getValueAt(fila, 0).toString());
    txtNombres.setText(tblAlumnos.getValueAt(fila, 1).toString());
    txtApellidos.setText(tblAlumnos.getValueAt(fila, 2).toString());
    txtDni.setText(tblAlumnos.getValueAt(fila, 3).toString());
    txtEdad.setText(tblAlumnos.getValueAt(fila, 4).toString());
    txtCelular.setText(tblAlumnos.getValueAt(fila, 5).toString());
    lblEstado2.setText(tblAlumnos.getValueAt(fila, 6).toString());

    txtDni.setEditable(false); // 🔒 NO permitir cambiar DNI en alumnos existentes
    txtCodAlumno.setEditable(false); // por si acaso también
    }//GEN-LAST:event_tblAlumnosMouseClicked

    private void txtCodAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellidos2;
    private javax.swing.JLabel lblCelular2;
    private javax.swing.JLabel lblCodAlumno2;
    private javax.swing.JLabel lblDni2;
    private javax.swing.JLabel lblEdad2;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblNombres2;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo9;
    private javax.swing.JPanel panelAlumno;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodAlumno;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}